Neos:
  Form:
    presets:
      default:
        formElementTypes:
          'Alan.Neos:Captcha':
            superTypes:
              'Neos.Form:FormElement': true
              'Neos.Form:TextMixin': true
            implementationClassName: Alan\Neos\FormElements\Captcha
            renderingOptions:
              templatePathPattern: 'resource://Alan.Neos/Private/Form/Captcha.html'
  Neos:
    fusion:
      autoInclude:
        'Alan.Neos': true
    userInterface:
      translation:
        autoInclude:
          'Alan.Neos':
            - 'NodeTypes/*'
  FluidAdaptor:
    namespaces:
      alan:
        - 'Alan\Neos\ViewHelpers'
