Alan:
  Neos:
    apiKey: 'dSUr0wIrOpf33tnGcsAYfPKQtMSY64Ja41OPqpNt' # put your api key here
    siteKey: 'gYzTBsfqz0HEShrSO3BrQwPWuYmr13YV3FfU4oIe'
#    animator: 'resource://Alan.Neos/Private/Images/animator.svg'
