Neos:
  Form:
    presets:
      default:
        formElementTypes:
          'Alan.NeosForm.Form:Captcha':
            superTypes:
              'Neos.Form:FormElement': true
            implementationClassName: Alan\NeosForm\FormElements\Captcha
            renderingOptions:
              templatePathPattern: 'resource://Alan.NeosForm/Private/Form/Captcha.html'
  Neos:
    fusion:
      autoInclude:
        'Alan.NeosForm': true
    userInterface:
      translation:
        autoInclude:
          'Alan.NeosForm':
            - 'NodeTypes/*'
  FluidAdaptor:
    namespaces:
      alan-form:
        - 'Alan\NeosFrom\ViewHelpers'
