Alan:
  Neos:
    apiKey: 'GoEDBgTM5LA7xuL6q6LzySK9InQb1gpr5LiA3jwB' # put your api key here
    siteKey: 'lxzGsia8PlMAriIW3tm7V6iAEAunOZQObhRjQ6Cf'
#    animator: 'resource://Alan.Neos/Private/Images/animator.svg'
